2025-09-18 23:27:38,513 - INFO - Assets path configured: C:\Users\Administrador\view-upgrade\assets
2025-09-18 23:27:38,517 - INFO - Starting up TCP server on localhost:52329
2025-09-18 23:27:38,525 - INFO - Flet app has started...
2025-09-18 23:27:38,528 - INFO - App URL: tcp://localhost:52329
2025-09-18 23:27:38,528 - INFO - Starting Flet View app...
2025-09-18 23:27:38,529 - INFO - Looking for Flet executable at: C:\Users\Administrador\AppData\Local\Programs\Python\Python312\Lib\site-packages\flet_desktop\app\flet\flet.exe
2025-09-18 23:27:38,529 - INFO - Flet View found in: C:\Users\Administrador\AppData\Local\Programs\Python\Python312\Lib\site-packages\flet_desktop\app\flet\flet.exe
2025-09-18 23:27:38,869 - INFO - App session started
2025-09-18 23:27:38,877 - ERROR - ler_planilha: [Errno 2] No such file or directory: 'C:\\Users\\Arklok\\OneDrive - Quality Software SA\\Documentos\\Agendamentos_Rollout_2025_SO.xlsx'
2025-09-18 23:28:29,179 - INFO - Assets path configured: C:\Users\Administrador\view-upgrade\assets
2025-09-18 23:28:29,181 - INFO - Starting up TCP server on localhost:59859
2025-09-18 23:28:29,185 - INFO - Flet app has started...
2025-09-18 23:28:29,186 - INFO - App URL: tcp://localhost:59859
2025-09-18 23:28:29,187 - INFO - Starting Flet View app...
2025-09-18 23:28:29,187 - INFO - Looking for Flet executable at: C:\Users\Administrador\AppData\Local\Programs\Python\Python312\Lib\site-packages\flet_desktop\app\flet\flet.exe
2025-09-18 23:28:29,188 - INFO - Flet View found in: C:\Users\Administrador\AppData\Local\Programs\Python\Python312\Lib\site-packages\flet_desktop\app\flet\flet.exe
2025-09-18 23:28:29,390 - INFO - App session started
2025-09-18 23:28:29,394 - ERROR - ler_planilha: [Errno 13] Permission denied: 'C:\\Users\\Administrador\\OneDrive\\RolloutMirror'
2025-09-18 23:28:59,248 - INFO - Assets path configured: C:\Users\Administrador\view-upgrade\assets
2025-09-18 23:28:59,250 - INFO - Starting up TCP server on localhost:59867
2025-09-18 23:28:59,254 - INFO - Flet app has started...
2025-09-18 23:28:59,256 - INFO - App URL: tcp://localhost:59867
2025-09-18 23:28:59,256 - INFO - Starting Flet View app...
2025-09-18 23:28:59,256 - INFO - Looking for Flet executable at: C:\Users\Administrador\AppData\Local\Programs\Python\Python312\Lib\site-packages\flet_desktop\app\flet\flet.exe
2025-09-18 23:28:59,257 - INFO - Flet View found in: C:\Users\Administrador\AppData\Local\Programs\Python\Python312\Lib\site-packages\flet_desktop\app\flet\flet.exe
2025-09-18 23:28:59,467 - INFO - App session started
2025-09-18 23:29:00,828 - ERROR - to_time_safe: hour must be in 0..23
2025-09-18 23:36:34,866 - INFO - Assets path configured: C:\Users\Administrador\view-upgrade\assets
2025-09-18 23:36:34,868 - INFO - Starting up TCP server on localhost:61201
2025-09-18 23:36:34,878 - INFO - Flet app has started...
2025-09-18 23:36:34,880 - INFO - App URL: tcp://localhost:61201
2025-09-18 23:36:34,880 - INFO - Starting Flet View app...
2025-09-18 23:36:34,881 - INFO - Looking for Flet executable at: C:\Users\Administrador\AppData\Local\Programs\Python\Python312\Lib\site-packages\flet_desktop\app\flet\flet.exe
2025-09-18 23:36:34,881 - INFO - Flet View found in: C:\Users\Administrador\AppData\Local\Programs\Python\Python312\Lib\site-packages\flet_desktop\app\flet\flet.exe
2025-09-18 23:36:35,381 - INFO - App session started
2025-09-18 23:42:32,921 - INFO - Assets path configured: C:\Users\Administrador\view-upgrade\assets
2025-09-18 23:42:32,925 - INFO - Starting up TCP server on localhost:53145
2025-09-18 23:42:32,942 - INFO - Flet app has started...
2025-09-18 23:42:32,945 - INFO - App URL: tcp://localhost:53145
2025-09-18 23:42:32,945 - INFO - Starting Flet View app...
2025-09-18 23:42:32,947 - INFO - Looking for Flet executable at: C:\Users\Administrador\AppData\Local\Programs\Python\Python312\Lib\site-packages\flet_desktop\app\flet\flet.exe
2025-09-18 23:42:32,948 - INFO - Flet View found in: C:\Users\Administrador\AppData\Local\Programs\Python\Python312\Lib\site-packages\flet_desktop\app\flet\flet.exe
2025-09-18 23:42:33,248 - INFO - App session started
2025-09-18 23:42:33,258 - ERROR - ler_planilha: [Errno 2] No such file or directory: 'C:\\Users\\Arklok\\OneDrive - Quality Software SA\\Documentos\\Agendamentos_Rollout_2025_SO.xlsx'
2025-09-18 23:43:02,119 - INFO - Assets path configured: C:\Users\Administrador\view-upgrade\assets
2025-09-18 23:43:02,121 - INFO - Starting up TCP server on localhost:56890
2025-09-18 23:43:02,126 - INFO - Flet app has started...
2025-09-18 23:43:02,127 - INFO - App URL: tcp://localhost:56890
2025-09-18 23:43:02,127 - INFO - Starting Flet View app...
2025-09-18 23:43:02,128 - INFO - Looking for Flet executable at: C:\Users\Administrador\AppData\Local\Programs\Python\Python312\Lib\site-packages\flet_desktop\app\flet\flet.exe
2025-09-18 23:43:02,128 - INFO - Flet View found in: C:\Users\Administrador\AppData\Local\Programs\Python\Python312\Lib\site-packages\flet_desktop\app\flet\flet.exe
2025-09-18 23:43:02,337 - INFO - App session started
2025-09-18 23:43:02,723 - ERROR - to_time_safe: hour must be in 0..23
2025-09-18 23:46:16,010 - INFO - Assets path configured: C:\Users\Administrador\view-upgrade\assets
2025-09-18 23:46:16,013 - INFO - Starting up TCP server on localhost:61975
2025-09-18 23:46:16,019 - INFO - Flet app has started...
2025-09-18 23:46:16,021 - INFO - App URL: tcp://localhost:61975
2025-09-18 23:46:16,021 - INFO - Starting Flet View app...
2025-09-18 23:46:16,022 - INFO - Looking for Flet executable at: C:\Users\Administrador\AppData\Local\Programs\Python\Python312\Lib\site-packages\flet_desktop\app\flet\flet.exe
2025-09-18 23:46:16,022 - INFO - Flet View found in: C:\Users\Administrador\AppData\Local\Programs\Python\Python312\Lib\site-packages\flet_desktop\app\flet\flet.exe
2025-09-18 23:46:16,261 - INFO - App session started
2025-09-18 23:46:16,661 - ERROR - to_time_safe: hour must be in 0..23
2025-09-18 23:51:18,012 - ERROR - to_time_safe: hour must be in 0..23
2025-09-18 23:52:51,067 - INFO - Assets path configured: C:\Users\Administrador\view-upgrade\assets
2025-09-18 23:52:51,070 - INFO - Starting up TCP server on localhost:55773
2025-09-18 23:52:51,076 - INFO - Flet app has started...
2025-09-18 23:52:51,079 - INFO - App URL: tcp://localhost:55773
2025-09-18 23:52:51,079 - INFO - Starting Flet View app...
2025-09-18 23:52:51,080 - INFO - Looking for Flet executable at: C:\Users\Administrador\AppData\Local\Programs\Python\Python312\Lib\site-packages\flet_desktop\app\flet\flet.exe
2025-09-18 23:52:51,080 - INFO - Flet View found in: C:\Users\Administrador\AppData\Local\Programs\Python\Python312\Lib\site-packages\flet_desktop\app\flet\flet.exe
2025-09-18 23:52:51,337 - INFO - App session started
2025-09-18 23:52:51,342 - ERROR - ler_planilha: [Errno 2] No such file or directory: 'C:\\Users\\Adminstrador\\Downloads\\Agendamentos_Rollout_2025_SO.xlsx'
2025-09-18 23:53:17,456 - INFO - Assets path configured: C:\Users\Administrador\view-upgrade\assets
2025-09-18 23:53:17,458 - INFO - Starting up TCP server on localhost:50434
2025-09-18 23:53:17,462 - INFO - Flet app has started...
2025-09-18 23:53:17,464 - INFO - App URL: tcp://localhost:50434
2025-09-18 23:53:17,464 - INFO - Starting Flet View app...
2025-09-18 23:53:17,464 - INFO - Looking for Flet executable at: C:\Users\Administrador\AppData\Local\Programs\Python\Python312\Lib\site-packages\flet_desktop\app\flet\flet.exe
2025-09-18 23:53:17,465 - INFO - Flet View found in: C:\Users\Administrador\AppData\Local\Programs\Python\Python312\Lib\site-packages\flet_desktop\app\flet\flet.exe
2025-09-18 23:53:17,669 - INFO - App session started
2025-09-18 23:53:18,051 - ERROR - to_time_safe: hour must be in 0..23
2025-09-18 23:58:18,274 - ERROR - to_time_safe: hour must be in 0..23
2025-09-19 00:03:18,532 - ERROR - to_time_safe: hour must be in 0..23
